[project]
name = "personal-libraray-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.11.5",
    "sqlalchemy>=2.0.40",
    "streamlit>=1.44.1",
]
